### ISSUE TITLE
Web API not showing data today

### ISSUE THREAD

**Issue by nolashade** [loisaidasam/the-masters-api#1]
Hi Sam,

I am using your awesome API for our neighborhood Master's tournament and the API is down this morning. Any idea what's going on? Thanks for this.

**Comment by jlars1621** [comment]
Hey Sam - Same issue on my end - hopefully it is a quick fix! 

Taking a peak in the Dev Tools console, seems to throw an error related to "document.body.removeChild(jfContent) ;" 

(Line 64 in the content.js)

Otherwise, this API has been great!

**Comment by loisaidasam** [comment]
Sorry about that. Issue on my end - we're back!

**Comment by jlars1621** [comment]
![img_3121](https://user-images.githubusercontent.com/38168151/38468764-44db6e96-3b10-11e8-8214-7e94dfac9dd8.jpg)

up and running again! thanks Sam!
