### ISSUE TITLE
Will the API be back for 2021??

### ISSUE THREAD

**Issue by jlars1621** [loisaidasam/the-masters-api#10]
I Saw Ross' previous comment he sourced his own method to ping the espn leaderboard, but wanted to see if perhaps this was going to be spun up again! 

Justin

**Comment by Rossimac** [comment]
Happy for you to use my version

[https://masters.karlasretirementfund.me/data_scores.json](https://masters.karlasretirementfund.me/data_scores.json)

Westwood and McIlroy are killing me!

**Comment by jlars1621** [comment]
Much appreciated @Rossimac ! 

I threw Rose on my list, so I'm hoping he can keep pace - Thanks again!!

**Comment by jlars1621** [comment]
Thanks again for letting me tap into your Web API - worked great!

Didn't win my pool, but happy to see Matsuyama win - until next year!

**Comment by loisaidasam** [comment]
Sorry for the delay. I commented in #11 as well. See you next year!
