### ISSUE TITLE
Any chance to get the service running for 2021? 

### ISSUE THREAD

**Issue by mthees7** [loisaidasam/the-masters-api#11]
Looks like the parser is correct for ESPN's leaderboard, just not sure if the script is currently pulling new info.

**Comment by loisaidasam** [comment]
Hello @mthees7 and the other folks who asked 👋

Unfortunately this year The Masters aligned with my kiddos being on spring break and a family trip, so I wasn't able to put something together. 

Hopefully folks figured out alternative solutions!
