### ISSUE TITLE
data collection seems to be failing..

### ISSUE THREAD

**Issue by mthees7** [loisaidasam/the-masters-api#4]
`{
  "last_updated": "1555078441",
  "last_updated_str": "2019-04-12T10:14:01-0400",
  "data_source": "http://www.espn.com/golf/leaderboard",
  "players": [
    {
      "player": null,
      "pos": "T1",
      "r1": "10:42 AM",
      "r2": "66",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-6",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T1",
      "r1": "11:04 AM",
      "r2": "66",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-6",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "3",
      "r1": "10:53 AM",
      "r2": "67",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-5",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T4",
      "r1": "9:58 AM",
      "r2": "68",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-4",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T4",
      "r1": "10:42 AM",
      "r2": "68",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-4",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T6",
      "r1": "1",
      "r2": "69",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-3",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T6",
      "r1": "1",
      "r2": "69",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-3",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T6",
      "r1": "11:48 AM",
      "r2": "69",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T6",
      "r1": "1:05 PM",
      "r2": "69",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T6",
      "r1": "1:49 PM",
      "r2": "69",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "7",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "4",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "2",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "10:09 AM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "10:42 AM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "11:15 AM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "12:10 PM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "12:32 PM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "1:38 PM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "1:49 PM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "2:00 PM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T11",
      "r1": "2:00 PM",
      "r2": "70",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T23",
      "r1": "1",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-1",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T23",
      "r1": "9:58 AM",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T23",
      "r1": "12:54 PM",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T23",
      "r1": "1:27 PM",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T23",
      "r1": "1:27 PM",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T23",
      "r1": "1:38 PM",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "-1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "4",
      "r2": "71",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "+1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "10:31 AM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "11:15 AM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "11:26 AM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "11:26 AM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "11:37 AM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "12:10 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "12:32 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "12:32 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "1:05 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "1:16 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "1:16 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "1:27 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T29",
      "r1": "1:49 PM",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "E",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "5",
      "r2": "72",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "+1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "2",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "1",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "10:09 AM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "10:09 AM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "10:31 AM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "10:53 AM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "11:59 AM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "12:43 PM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "12:54 PM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "1:16 PM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "1:38 PM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T43",
      "r1": "2:00 PM",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+1",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "6",
      "r2": "74",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "6",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "+1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "6",
      "r2": "74",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "2",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "9:58 AM",
      "r2": "74",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "12:43 PM",
      "r2": "74",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T56",
      "r1": "12:54 PM",
      "r2": "74",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+2",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "7",
      "r2": "73",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "+2",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "7",
      "r2": "76",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "2",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "2",
      "r2": "76",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "1",
      "r2": "76",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "10:31 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "10:53 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "11:04 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "11:15 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "11:48 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "11:59 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "11:59 AM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T63",
      "r1": "1:05 PM",
      "r2": "75",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+3",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "76",
      "r1": "5",
      "r2": "76",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+4",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "Projected Cut",
      "r1": null,
      "r2": null,
      "r3": null,
      "r4": null,
      "tot": null,
      "to_par": null,
      "today": null,
      "thru": null,
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T77",
      "r1": "2",
      "r2": "78",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+5",
      "thru": "-1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T77",
      "r1": "11:37 AM",
      "r2": "77",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+5",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T77",
      "r1": "12:43 PM",
      "r2": "77",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+5",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T80",
      "r1": "5",
      "r2": "77",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+6",
      "thru": "+1",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T80",
      "r1": "11:37 AM",
      "r2": "78",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+6",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T80",
      "r1": "12:10 PM",
      "r2": "78",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+6",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T83",
      "r1": "1",
      "r2": "80",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+8",
      "thru": "E",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T83",
      "r1": "11:26 AM",
      "r2": "80",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+8",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T85",
      "r1": "4",
      "r2": "78",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+9",
      "thru": "+3",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "T85",
      "r1": "11:04 AM",
      "r2": "81",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+9",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    },
    {
      "player": null,
      "pos": "87",
      "r1": "11:48 AM",
      "r2": "82",
      "r3": "--",
      "r4": "--",
      "tot": "--",
      "to_par": null,
      "today": "+10",
      "thru": "-",
      "link": null,
      "country_flag_image": null
    }
  ]
}`

Returning each player as null.

**Comment by TeeJay942** [comment]
Agreed, the latest commit didnt fix the column issue.

**Comment by loisaidasam** [comment]
Fixed via #2
