### ISSUE TITLE
The columns have been updated again and the api is pulling "null" for player names

### ISSUE THREAD

**Issue by mthees7** [loisaidasam/the-masters-api#5]
Looks like espn changed columns with the final result.

**Comment by mthees7** [comment]
Seems like the movement column has just been removed, could be easy enough just to do a rollback.

**Comment by loisaidasam** [comment]
Instead of changing the parser again, I reverted to the last good/working result, and am leaving it here:

http://samsandberg.com/themasters/

Way to go Tiger!
